### ISSUE TITLE
Plugin obsolete, Android will publish app with targetSdkVersion=26

### ISSUE THREAD

**Issue by carlo318** [izee/cordova-plugin-serialport#2]
Hi there,
this plugin works very well but only if the App has the target sdk declaration:
`
<preference name="android-targetSdkVersion" value="22"/>
`
Android Play Store has started the obsolete warning, that from august 2018 all Android apps must have target Sdk = 26
`
<preference name="android-targetSdkVersion" value="26"/>
`
But this plugin doesn't work with target Sdk 23 or above.
Anyone knows how to upgrade/fix, or what other plugin or dll is needed?
Thankyou.
Carlo

**Comment by izee** [comment]
Which version of `Cordova Android` ?

**Comment by carlo318** [comment]
I am using: 
- Cordova 6.5.0 
- Android platform  6.1.2

But I guess the problem is with almost any version. 
Maybe the problem is in *.so library which is not supported on Api above 22.

**Comment by victorsosa** [comment]
I am having the same issue, thanks

**Comment by izee** [comment]
I think you need upgrade `Cordova Android` to 6.3.0 or above.
http://cordova.apache.org/announcements/2017/09/27/android-release.html

**Comment by victorsosa** [comment]
I am using 6.4.0 and I am getting this issue

**Comment by carlo318** [comment]
I think it is not a matter of Cordova Android version.
Android Studio, on openPort(), reports the error:  "libserial_port.so has text relocations". See error below:

`
07-04 14:54:53.168 4072-4142/? E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: com.company.myapp, PID: 4072
    java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.company.myapp-1/lib/arm/libserial_port.so: has text relocations
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at android_serialport_api.SerialPort.<clinit>(SerialPort.java:83)
        at me.izee.cordova.plugin.NativeSerial.openPort(NativeSerial.java:135)
        at me.izee.cordova.plugin.NativeSerial.access$000(NativeSerial.java:24)
        at me.izee.cordova.plugin.NativeSerial$1.run(NativeSerial.java:39)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
`

**Comment by victorsosa** [comment]
Base on that error, it seems like the DLL path is not been loaded.

Check out this explain: https://stackoverflow.com/questions/1403788/java-lang-unsatisfiedlinkerror-no-dll-in-java-library-path#1403808

**Comment by carlo318** [comment]
Hi @victorsosa  I don't understand why the path should be wrong.
As written above, the plugin works fine if I specify  android-targetSdkVersion=22  in my APP, so any path to the Library is correct.
If I change only   android-targetSdkVersion=26   in my APP, without changing anything in the plugin and in the APP, Java raises the error "UnsatisfiedLinkError: text relocations".
I don't know how to change the plugin, if it needs a different way to access the "dll path", with SDKVersion 26. Probably it is a problem on how the  libserial_port.so has been written, or the way the new SDK 26 accesses these libraries.

**Comment by izee** [comment]
support sdk 23 or above , I think need to rebuild `libserial_port.so` file with out `text relocations`.
*.so file is got from [here](https://code.google.com/archive/p/android-serialport-api/).

[api changes](https://developer.android.google.cn/about/versions/marshmallow/android-6.0-changes#behavior-runtime)  and related [guide](https://wiki.gentoo.org/wiki/Hardened/Textrels_Guide).

**Comment by victorsosa** [comment]
@izee yep, that would fix the issue.

**Comment by victorsosa** [comment]
I was trying to do the rebuild but the repo is gone:
http://android-serialport-api.googlecode.com/svn/trunk/android-serialport-api

So I download the source code zip file. I have it to compile, but I need to check that the build doesn't include the 

> text relocation

using the guide (a lot to read)

**Comment by victorsosa** [comment]
Build result:
```
[vns@betito project]$ ndk-build
[armeabi] Compile thumb  : serial_port <= SerialPort.c
[armeabi] SharedLibrary  : libserial_port.so
[armeabi] Install        : libserial_port.so => libs/armeabi/libserial_port.so
[armeabi-v7a] Compile thumb  : serial_port <= SerialPort.c
[armeabi-v7a] SharedLibrary  : libserial_port.so
[armeabi-v7a] Install        : libserial_port.so => libs/armeabi-v7a/libserial_port.so
[x86] Compile        : serial_port <= SerialPort.c
[x86] SharedLibrary  : libserial_port.so
[x86] Install        : libserial_port.so => libs/x86/libserial_port.so
```


scan result:
```
[vns@betito project]$ scanelf -qT ./libs/armeabi/libserial_port.so | wc -l
0
[vns@betito project]$ scanelf -qT ./libs/armeabi-v7a/libserial_port.so | wc -l
0
[vns@betito project]$ scanelf -qT ./libs/x86/libserial_port.so | wc -l
0
```
 thats until now everything seems ok

**Comment by carlo318** [comment]
@victorsosa how did you get to rebuild the .so file? 
Can you share it, so we can try to include it in this plugin and see if it compiles and works in cordova?

**Comment by victorsosa** [comment]
Yes, I did; please check if the compile works

https://drive.google.com/open?id=1DYPZV9RVVe5t0haIfx-LzHixlySIEZip

those are the dll files so you overwrite them.

**Comment by carlo318** [comment]
@victorsosa I have substituted the .so files from your package and it works perfectly, also with targetSdkVersion = 26.
Thankyou very much for sharing!

**Comment by victorsosa** [comment]
@izee  PR created please merge

**Comment by carlo318** [comment]
@victorsosa sorry for my ignorance, but the .so files you sent me to test, are about 63KB in size (armeabi). The commited .so files are 13KB. 
What is the difference? Just another way of compiling (debug/release) or compression?

**Comment by victorsosa** [comment]
@carlo318 you are right; I will fix that as soon I can

**Comment by victorsosa** [comment]
@carlo318 DONE

**Comment by carlo318** [comment]
Thankyou!
