### ISSUE TITLE
How do I install the plugin?

### ISSUE THREAD

**Issue by moonlitangel** [izee/cordova-plugin-serialport#8]
Hello.

`cordova plugin add path or git address`

`(node:7544) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Invalid Plugin! C:\Users\thfql\Documents\ng2_start\serialtest\plugins\cordova-plugin-serialport needs a valid package.json
(node:7544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, 
promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
I tried to install it. But the wrong plug-in!have been printed out of

I want to install this plug-in.

**Comment by victorsosa** [comment]
`cordova plugin add https://github.com/izee/cordova-plugin-serialport.git`

**Comment by moonlitangel** [comment]
> `cordova plugin add https://github.com/izee/cordova-plugin-serialport.git`

I use codeova 8.0.0
The command fails to operate. npm err.
I did it myself.

It works right.
I've been through many failures.
But it succeeded.
Thank you for your answer.

**Comment by moonlitangel** [comment]
This plug-in is not registered in npm.
That's why I can't install In Cordova 8.
I moved to my plugin folder.
And then modified config.xml and package.json.

to config.xml
`<plugin name="cordova-plugin-serialport" spec="./plugins/cordova-plugin-serialport" />`

to package.json
```"cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-serialport": {}
    },
    "platforms": [
      "android"
    ]
  }
```
